version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iding_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/iding_development
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/rails

volumes:
  postgres_data:
