# 本機執行 docker compose -f compose-dev.yaml up 啟動開發環境
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      # 連接到本機的 PostgreSQL (預設 port 5432)
      # host.docker.internal 是一個特殊名稱，可以用來解析宿主機器的IP
      DATABASE_URL: postgres://wubingyan@host.docker.internal:5432/iding_development
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
